

volumes:
  node_modules: {}
  mongo_data: {}
  mongo_log: {}


networks:
  app-network:
    driver: bridge

services:
  # redis:
  #   image: redis:7.4.0-alpine3.20
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ./redis.conf:/usr/local/etc/redis/redis.conf
  #     - ./redis_data:/data
  #   command: redis-server /usr/local/etc/redis/redis.conf
  #   environment:
  #     - HOST=redis
  #   networks:
  #     - app-network
  #   restart: always
  
  
  mongo:
    image: mongo:7.0.14
    networks:
      - app-network
    restart: always
    environment:
      - HOST=mongo
    volumes:
      - mongo_data:/data/db
      - mongo_log:/data/log
    ports:
      - 127.0.0.1:27018:27017
  

  api-service:
    container_name: api-service
    build:
      context: .
      args:
        PKG: 'api-service'
      dockerfile: Dockerfile
    networks:
      - app-network
    env_file:
      - .env
    restart: always
    depends_on:
      - mongo
      - redis
    ports:
      - 8000:8000

  ai-service:
    container_name: ai-service
    build:
      context: .
      args:
        PKG: 'ai-service'
      dockerfile: Dockerfile
    networks:
      - app-network
    env_file:
      - .env
    restart: always
    depends_on:
      - mongo
      - redis
    ports:
      - 8001:8001 
  
