export const ONCHAIN_QUEUES = {
  QUEUE_REGISTER_NAME: 'QUEUE_REGISTER_NAME',
  QUEUE_TRANSFER_NAME: 'QUEUE_TRANSFER_NAME',
  QUEUE_RENEW_NAME: 'QUEUE_RENEW_NAME',
  QUEUE_TEXT_CHANGED: 'QUEUE_TEXT_CHANGED',

  QUEUE_UPDATE_IPASSET_METADATA: 'QUEUE_IPASSET_METADATA',
};

export const ONCHAIN_JOBS = {
  JOB_REGISTER_NAME: 'JOB_REGISTER_NAME',
  JOB_TRANSFER_NAME: 'JOB_TRANSFER_NAME',
  JOB_RENEW_NAME: 'JOB_RENEW_NAME',
  JOB_TEXT_CHANGED: 'JOB_TEXT_CHANGED',

  JOB_UPDATE_IPASSET_METADATA: 'JOB_UPDATE_IPASSET_METADATA',
};

export const MQ_JOB_DEFAULT_CONFIG = {
  removeOnComplete: true,
  removeOnFail: {
    count: 1000, // keep up to 1000 jobs
  },
  attempts: 5,
  backoff: {
    type: 'exponential',
    delay: 1000,
  },
};
